### ISSUE TITLE
Have you seen the new `partial_compress` method?

### ISSUE THREAD

**Issue by corneliusroemer** [MDU-PHL/pango-collapse#2]
Didn't know you were making such good use of the little pango_aliasor package - didn't expect that!

I set up partial collapse yesterday to help keep the number of dots limited while teaching what the aliases mean.

Hence you can now compress B.1.1.529.5.2.1.1 to BA.5.2.1.1 instead of BF.1

Good choice of name "collapse" - better than my "compress" 👼 

see https://github.com/corneliusroemer/pango_aliasor/releases/tag/v0.2.0 for details

**Comment by Wytamma** [comment]
Hey @corneliusroemer yes thanks for such a great package! It’s solving a bunch of problems for us.

I did see partial compress but couldn’t get it to go exactly what we wanted. We need to collapse all sub lineages up to a set of lineages that we can then report to the department of health. 

I’d be happy to contribute back anything we can! Just needed a CLI so it was easier to make this one instead of thinking of a way to make it work generally 😅

**Comment by corneliusroemer** [comment]
Great! Can you give an example of what you mean by collapse up to a certain
set?

It may be able to do that already or only with minor tweaks.

**Comment by Wytamma** [comment]
Essentially it's the `collapse` function here -> https://github.com/MDU-PHL/pango-collapse/blob/main/pango_collapse/collapsor.py#L9.  You could just copy and paste that into your `Aliasor` class as i'm subclassing it anyway. 

We have a set of lineages that we report to the department of health (e.g. https://github.com/MDU-PHL/pango-collapse/blob/main/pango_collapse/collapse.txt). All the sublineages of these lineages need to be collapsed into these lineages so that the report only contains the lineages in the `collapse.txt` file.
