### ISSUE TITLE
Should aliases be collapsed?

### ISSUE THREAD

**Issue by ammaraziz** [MDU-PHL/pango-collapse#6]
Hi Wytamma,

I've been seeing weird results in our reporting output. After scratching my head, it turns out `pango-collapse` is collapsing aliases into non-aliased lineages.  For example: `EG.1` is an alias of `XBB.1.9.2` which is on in `collapse.txt`.

The simple solution is to add the alias of `XBB.1.9.2` to `collapsed.txt` but this will require constant monitoring of aliases. Another solution is to check the alias key to see if any lineage on the collapsed list has an alias and if it does, return the alias.

This is probably super low on your priority list because of budget changes. If I have time I will try to submit a pull request (but this will be in August!).

Thanks,

Ammar

**Comment by ammaraziz** [comment]
Another example: `GA.1` collapsed into `XBB`. This one is especially confusing:

```
GA ->  XBB.1.17.1 -> XBB
```

**Comment by Wytamma** [comment]
Hey @ammaraziz, I think it’s the intended behaviour? [EG.1 is XBB.1.9.2.1](https://github.com/cov-lineages/pango-designation/blob/939990f5d4208ab6956dcc5a818cbe5d9886a430/lineage_notes.txt#L2817). So, if XBB.1.9.2 is in the collapse file all the sub-lineages should be collapsed up to XBB.1.9.2.

Same with GA.1... [GA.1 is XBB.1.17.1.1](https://github.com/cov-lineages/pango-designation/blob/939990f5d4208ab6956dcc5a818cbe5d9886a430/lineage_notes.txt#L2872). Because XBB is in the collapse file GA.1 is collapsed up to XBB. If any of the other lineages along the path from GA.1 to XBB were in the collapse file then GA.1 would only be collapsed up to that lineage.
